Use shutil.copytree instead of path.rename
In https://review.openstack.org/#/c/635686/ I got:

```
OSError: [Errno 39] Directory not empty
```

I'm not sure if that was a spurious error because we haven't hit it
before, but `shutil.copytree` is better suited for this anyway.